[platformio]
default_envs = glove_esp32

[env:glove_esp32]
platform = espressif32@6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200
platform_packages =
  framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32/archive/refs/tags/2.0.14.tar.gz
lib_extra_dirs =
  ../lib
lib_deps =
  adafruit/Adafruit MPU6050@^2.2.6
  adafruit/Adafruit Unified Sensor@^1.1.14
  adafruit/Adafruit BusIO@^1.16.1
build_flags =
  -D GD1_FIRMWARE_NAME=\"GD-1_Glove_FR1\"

[env:native]
platform = native
build_src_filter =
  +<GestureProcessor.cpp>
  -<main.cpp>
test_filter = test_gesture_processor
build_flags =
  -std=gnu++17
