[platformio]
default_envs = csi_node_esp32s3

[env:csi_node_esp32s3]
platform = espressif32@6.5.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
platform_packages =
  framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32/archive/refs/tags/2.0.14.tar.gz
build_flags =
  -D GD1_CSI_NODE_FIRMWARE=\"GD-1_CSI_Node\"

